# dvc.yaml
# Pipeline DVC para TelcoVision
# - process_data: preprocesa el dataset raw y genera el procesado
# - train: entrena el modelo y guarda artefactos y métricas

stages:
        data_prep:
            cmd: python src/data_prep.py --input data/raw/telco_churn.csv --out data/processed/telco_churn_processed.csv
            deps:
                - src/data_prep.py
                - data/raw/telco_churn.csv
            outs:
                - data/processed/telco_churn_processed.csv
    train:
        cmd: python src/train.py --params params.yaml
        deps:
            - src/train.py
            - data/processed/telco_churn_processed.csv
            - params.yaml
        outs:
            - models/model.joblib
        metrics:
            - models/metrics.json