
### params.yaml
# Configuración del pipeline TelcoVision
# - paths: rutas de entrada/salida de datos y artefactos
# - target: columna objetivo para predicción
# - split: parámetros de partición train/test
# - model: tipo y parámetros del modelo a entrenar

paths:
  processed_data: data/processed/telco_churn_processed.csv
  model_path: models/model.joblib
  metrics_path: models/metrics.json

target: churn

test_size: 0.2
random_state: 42

model:
  type: LogisticRegression
  parameters:
    max_iter: 1000
    C: 1.0
    penalty: l2
    solver: lbfgs
    class_weight: balanced
